In [24]:
# Using a regular for loop to generate a list of squares
liste_1 = []
for i in range(10):
    liste_1.append(i**2)
print(liste_1)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [212]:
liste_2 = [i**2 for i in range(10)]
print(liste_2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [242]:
lst = [[i+j
         for i in range(3)] for j in range(10)]
print(lst)


[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9], [8, 9, 10], [9, 10, 11]]


In [246]:
##Dict

In [282]:
dict ={
    '10':"abde",
    '11':"aaa",
    '12':"bb",
    '13':"cc"
}

In [316]:
prenoms = ['nn','kk','ll','yy']

In [318]:
dico = {k:v for k , v in enumerate(prenoms)}
print(dico)

{0: 'nn', 1: 'kk', 2: 'll', 3: 'yy'}


In [320]:
print(dico.keys())

dict_keys([0, 1, 2, 3])


In [344]:
ages = [24,23,10,62]
dic = {k:v for k , v in zip(ages,dict) if k>30}
print(dic)

{62: '13'}


In [422]:
import builtins
list = builtins.list

li = list(i**2 for i in range(10, 60) if i % 2 != 0)
print(li)

[121, 169, 225, 289, 361, 441, 529, 625, 729, 841, 961, 1089, 1225, 1369, 1521, 1681, 1849, 2025, 2209, 2401, 2601, 2809, 3025, 3249, 3481]


In [424]:
tuple_1 = tuple(i**2 for i in range(4))
print(tuple_1)

(0, 1, 4, 9)


In [472]:
y = "23"
y = int(y)
type(y)

int

In [490]:
hex(15)

'0xf'

In [506]:
x = int(input('Donner un number :'))
x + 10

Donner un number : 12


22

In [530]:
##Abdella
x = 30
ville = 'Paris'
messsage = "la temperateur est {} degC a {}".format(x,ville)
print(messsage)

la temperateur est 30 degC a Paris


In [546]:
import numpy as np
parametres = {
    "W1" : np.random.randn(2,4),
    "b1" : np.zeros((2,1)),
    "W2" : np.random.randn(2,2),
    "b2" : np.zeros((2,1))
}

In [566]:
for i in range(1,3):
    print('couche',i)
    print(parametres["W{}".format(i)])

couche 1
[[ 0.25528107  1.07340602 -0.21747229  0.48943101]
 [ 0.36061619 -0.80776112 -0.57699789 -0.40294412]]
couche 2
[[-0.17007663  0.70484527]
 [ 0.31963954 -1.23168838]]


In [36]:
f = open('C:\\Users\\abdel\\OneDrive\\Desktop\\.ipynb_checkpoints\\file.txt',"r")

In [38]:
f.write("abdellah")
f.close()

In [2]:
with open('C:\\Users\\abdel\\OneDrive\\Desktop\\.ipynb_checkpoints\\file.txt',"w") as f:
    for i in range(10):
        f.write(f"{i}^3 = {i**2}\n")

In [1]:
carres_paires = {str(i): i**2 for i in range(0, 20)}

with open('file.txt', 'w') as f:
    f.write(str(carres_paires))

In [25]:
import numpy as np 
tab = np.array([1,2,3,4,5,6,7])
tab = np.array([[1,2,3],[4,5,6]])
print('tablea initial:\n',tab,end='\n\n')
#ajouter Un au tableau initial
tab1 = tab+1
print('ajoutr un au tableau initail:\n',tab1 ,end='\n\n')
# muliplier tableau2 fois deux
tab2 = tab1*2
print('la multiplication de tablau 2 fois deux est:\n',tab,end='\n\n')
#produit scalaire
produit = np.dot(tab1,tab.T)
print('le produit scalaire entre tableau 1 et tablau 2 est :\n\n',produit,end="\n\n")
#Transpose de tableau 
tab3 = tab.T
print('la transpose de tableau 1 est:\n',tab3,end='\n\n')

tablea initial:
 [[1 2 3]
 [4 5 6]]

ajoutr un au tableau initail:
 [[2 3 4]
 [5 6 7]]

la multiplication de tablau 2 fois deux est:
 [[1 2 3]
 [4 5 6]]

le produit scalaire entre tableau 1 et tablau 2 est :

 [[20 47]
 [38 92]]

la transpose de tableau 1 est:
 [[1 4]
 [2 5]
 [3 6]]

